apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: space
data:
  DATABASE_NAME: space_db
  DATABASE_PASSWORD: mongoPassword
  DATABASE_USERNAME: mongoUser
  MONGO_INITDB_DATABASE: space_db
  MONGO_INITDB_ROOT_PASSWORD: 4dm1n
  MONGO_INITDB_ROOT_USERNAME: root
  init-mongo.sh: |
    #!/bin/bash
    echo "Creating mongo users..."

    mongosh admin --host localhost -u root -p 4dm1n <<-EOJS
      use ${DATABASE_NAME:-space_db};
      db.createUser({
        user: '${DATABASE_USERNAME:-mongoUser}',
        pwd: '${DATABASE_PASSWORD:-mongoPassword}',
        roles: [{role: 'readWrite', db: '${DATABASE_NAME:-space_db}'}, {role: 'dbAdmin', db: '${DATABASE_NAME:-space_db}'}]
      });
    EOJS
    echo "Mongo users created."